### ISSUE TITLE
Add support for more scripting languages

### ISSUE THREAD

**Issue by mitchtbaum** [poga/actix-lua#25]
**Is your feature request related to a problem? Please describe.**
Lua is only one good scripting language.  Others, especially native Rust ones would be good to support.

**Describe the solution you'd like**
Make each language a plugin or feature, perhaps.

**Describe alternatives you've considered**
Forking `actix-lua` to make `actix-otherlang`, but that would be very limited and stale.

**Additional context**
Some good looking languages: [Ullage](https://github.com/iwillspeak/ullage), [Molten](https://github.com/transistorfet/molten), [Rulox](https://github.com/mariosangiorgio/rulox), [Tox](https://github.com/Lapz/tox), and [SimpleJIT Demo](https://github.com/CraneStation/simplejit-demo).

**Comment by poga** [comment]
Embedding languages are, by design, tightly coupled with the host. They also have their own trade-offs, binding interfaces, memory management, performance profile,...etc. Switching to a new language is basically a total rewrite.

`actix-lua` picks Lua specially because:
1. coroutines make asynchronous programming easier.
2. sophisticated module cache and reloading.
3. Lightweight and easy to use.

So, I think this issue is too board and not actionable.

**Comment by mitchtbaum** [comment]
Okay.  Could you please advise then how to go about similarly embedding Ullage, for example?

**Comment by poga** [comment]
I have no experience in Ullage or other languages you've mentioned. Sorry.

**Comment by mitchtbaum** [comment]
Well, off course not.  Lua is 26 years old, and these Rust-based languages are on average 1 year old.  Ullage looks like the most interesting one.  If you have a couple min, I'd really appreciate your views on using one of these similar to how we're using Lua now.

**Comment by poga** [comment]
As I said, if you want to make bindings between actix and the language you want, you better off start from scratch.

It's unrelated to `actix-lua` and I can't help you with it.

**Comment by mitchtbaum** [comment]
Ok, ty @poga
