### ISSUE TITLE
Debug example

### ISSUE THREAD

**Issue by mitchtbaum** [poga/actix-lua#8]
A helpful addition to the examples would be something like this [PHP script to dump full HTTP request to file (method, HTTP headers and body)](https://gist.github.com/magnetikonline/650e30e485c0f91f2f40).

**Comment by poga** [comment]
The goal of `actix-lua` is to bring rust and lua together with actix's actor model. Yes, you can create a full-feature web framework with it. But it's not the main focus of this library.

If anyone is interested in writing web frameworks, I encourage you to experiment. I'm willing to help if you have any question or feedback.

For now, I'm closing this since this is out of the scope of `actix-lua`.
